[package]
name = "pluralistic-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "pluralistic_rs"
path = "src/lib.rs"

[[bin]]
name = "pluralistic"
path = "src/main.rs"
[dependencies]
arr_macro = "0.2.1"
rand = "0.8.5"
